### ISSUE TITLE
403 Error when deleting session from session service

### ISSUE THREAD

**Issue by Gabby-pxy** [PICMG/redfish_server_template#19]
**Description:** 
Whenever I run a session management test to delete a session inside the GUI, I get a 403 error response. I am using the config credentials of the "Administrator" and the password "test" for the user. I'm not sure if the DELETE request is correct (maybe I need to be another account, or just using the sessionid)?

This line returns 403 error: 
resp_terminate_session = requests.delete(session_delete_url, verify=False, auth=auth, headers=httpHeaders)

**To replicate the issue described, follow these steps:**

1. Checkout the session_management branch.

2. Ensure that the server is running.

3. Run the GUI configuration.

4. Once the GUI begins, execute the session_management_WIP tests.

5. Check the response content and status. It should return a status of 403.

------------------------------------------------------------------------------
Redfish specification for session termination: 

13.3.4.4 Session termination or logout
When the client logs out, the Redfish session terminates. The session terminates through a DELETE request to the Session resource defined in either the Location header URI or the session ID in the response data. This ability to DELETE a session through the Session resource enables an administrator with sufficient privileges to terminate other users' sessions from a different session. When a session is terminated, the service shall not affect independent connections established originally by this session for other purposes, such as connections for server-sent events or transferring an image for the update service.

**Comment by dsandy12** [comment]
I have been unable to verify the 403 error with my code.  The sequence I am using is:
1. Create a session using the Redfish login process.
2. Get the @odata.id of the first session in the SessionService/Sessions collection
3. Send a Delete request to the uri associated @odata.id from the previous step
Following this process, I get a 200 response from the server with the body of the response set to the resource that was deleted.
This has been verified to work with both session login as well as Basic Authentication.  Perhaps, this issue was fixed with the authentication fixes with BUG #17 .

I found that the post request to add a new session includes the clear text session password for the session within the body of the response.  This is consistent with the metadata description in the schema, however, the description text for the schema says that the value of the field should be returned as null.
