### ISSUE TITLE
PATCH for NULLStrings not changing inputs of fields (Finding)

### ISSUE THREAD

**Issue by cmunozgo** [PICMG/redfish_server_template#20]
In the Account resource after creating an account, if a PATCH is made to the Name or description of the account it does not update it. (SO far only tested to change the inputs to NULLStrings).

**Comment by dsandy12** [comment]
When i attempted to change the Name and Description properties of the ManagerAccount using a PATCH operation to any value, the values are not changed.  This is expected behavior.  The reason for this is that the ManagerAccount schema defines these fields as readonly.  They can only be defined at resource creation time with a POST operation.
Whenever a post operation fails, check the message body in the POST response.  There should be Redfish Extended Error information that will help you diagnose the issue.
