### ISSUE TITLE
Thorough Bug Report of Schema Validation Results

### ISSUE THREAD

**Issue by AndrewErting** [PICMG/redfish_server_template#31]
# Schema Validation Failures
## Description
A number of resources fail to correctly validate against their CSDL representations with the current and most recent versions of the relevant repositories.
### Commit Links of Repositories During Test:
- [redfish_server_template](https://github.com/CaydenMurphree/RedFish_Capstone/commit/25ed30a518a5c48751da66cbce132c716e21a1a0)
- [redfish_server_maker](https://github.com/PICMG/redfish_server_maker/commit/36820843343d59cca35e4b1ec0ca7c8fa6a63880)
- [IIOT_mockup](https://github.com/PICMG/IIOT_2_mockup/commit/a6a4dc8b84c8133d645f74081f79aac15a687b4d)
- [IIOT_schema](https://github.com/PICMG/IIOT_2_schema/commit/a35fa06060853071a60c7fec6273a6c0a5d67af5)
- [Redfish Schema Bundle v2023.3](https://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2023.3.zip)

## Replication Steps:
1. Download listed versions of resources and repositories.
2. Follow installation and initialization steps from both both the server_maker and server_template.
3. Open a terminal in the redfish_server_template directory and run the command "mvn spring-boot:run"
4. From the same directory run the command "python3 Tests/util/TestHandler.py"
5. Find log named "refCrawlerLog.txt" in the Logs directory of the server_template folder.

**Note: Only on this particular commit does the command in step 4 apply.**

Additionally, see attached log for the output this code generated for me:
[refCrawlerLog.txt](https://github.com/PICMG/redfish_server_template/files/14673007/refCrawlerLog.txt)

**Comment by dsandy12** [comment]
@AndrewErting I have reviewed the bug report and have found many false positives.  In particular, there are many false positives related to missing fields that are being considered as having null values.  These two are different.  A missing field should generate an error if it is required but not present.  On the other hand, the check for null, is performed on the value of fields that are present.

@odata.context is not a required field, and appears to be a false failure on your test report.

The unreachable resources are due to missing permissions in the Privilege Table.  This will be logged in an error against either the schema or mockup builder.

since there are no actual errors related to this code, this issue will be closed.

**Comment by dsandy12** [comment]
Closed after investigation.  Error report shows false failures.
